---

- name: Create database for each site
  mysql_db: >
    name={{ wp_db_name }}
    state=present
    login_host={{ wp_db_host }}
    login_user={{ wp_db_user}}
    login_password={{ wp_db_password }}
  register: wp_mysql_db_create

- name: Copy saved database to server
  copy: >
    src={{ wp_database_backup }}
    dest=/tmp/{{ wp_site_name }}.sql
    login_user={{ wp_db_user}}
    login_password={{ wp_db_password }}
  when: wp_mysql_site_restore_saved_db|bool

- name: Import saved database
  mysql_db: >
    name={{ wp_db_name }}
    state=import
    target=/tmp/{{ wp_site_name }}.sql
    login_host={{ wp_db_host }}
    login_user={{ wp_db_user}}
    login_password={{ wp_db_password }}
  when: wp_mysql_site_restore_saved_db|bool

- name: Create/assign database user to db and grant permissions
  mysql_user: >
    name={{ wp_db_user }}
    password={{ wp_db_password }}
    priv='{{ wp_db_name }}.*:ALL'
    state=present
    login_host={{ wp_db_host }}
    login_user={{ wp_db_user}}
    login_password={{ wp_db_password }}
